language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_install:
  - composer self-update

install: composer install --dev

script: vendor/bin/phpunit -c tests/phpunit.xml

notifications:
  email: dev@megaweb.hu
