language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

install: composer install --no-dev

script: phpunit --bootstrap tests/Bootstrap.php tests

notifications:
  email: false
